name: test

on: [push, pull_request]
jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.0'
      id: go
    - name: Run unit tests
      run: go test ./...
