name: test

on: [push, pull_request]
jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.17.2
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.2
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run unit tests
      run: go test ./...
